config/routes.rb
Rails.application.routes.draw do


  get 'message/create'
  root 'pages#home'
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: "users"
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: "request_offers"
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'

  get '/calendar', to: 'pages#calendar'
  get '/settings/payment', to: 'users#payment', as: "settings_payment"
  get '/settings/payout', to: 'users#payout', as: "settings_payout"
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: "checkout"
  get '/earnings', to: 'users#earnings', as: "earnings"
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"

  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: "update_payment"
  post '/settings/payout', to: 'users#update_payout', as: "update_payout"
  post '/users/withdraw', to: 'users#withdraw', as: "withdraw"
  post '/messages', to: 'messages#create'

  put '/orders/:id/complete', to:'orders#complete', as:'complete_order'
  put '/offers/:id/accept', to:'offers#accept', as:'accept_offer'
  put '/offers/:id/reject', to:'offers#reject', as:'reject_offer'

  mount ActionCable.server => '/cable'

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end

    resources :orders, only: [:create]
  end

  resources :requests

  devise_for :users,
              path: '',
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: "logout"},
              controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :gigs
  has_many :requests
  has_many :offers

  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence:true, length: {maximum:50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(seller_id: params[:id]).order("created_at desc")
  end

  def update
    @user = current_user
    if @user.update_attributes(current_user_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot update..."
    end
    redirect_to dashboard_path
  end



  def update_payment
    if !current_user.stripe_id
      customer = Stripe::Customer.create(
        email: current_user.email,
        source: params[:stripeToken]
      )
    else
      customer = Stripe::Customer.update(
        current_user.stripe_id,
        source: params[:stripeToken]
      )
    end

    if current_user.update(stripe_id: customer.id, stripe_last_4: customer.sources.data.first["last4"])
      flash[:notice] = "New card is saved"
    else
      flash[:alert] = "Invalid card"
    end
    redirect_to request.referrer
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to request.referrer
  end

  def update_payout
    if current_user.update(paypal: params[:paypal])
      flash[:notice] = "Update payout successfully"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_to request.referrer
  end

def earnings
  @net_income = (Transaction.where("seller_id = ?", current_user.id).sum(:amount)/ 1.1).round(2)
  @withdrawn = Transaction.where("buyer_id = ? AND status = ? AND transaction_type= ?",
                                  current_user.id,
                                  Transaction.statuses[:approved],
                                  Transaction.transaction_types[:withdraw]
                                  ).sum(:amount)

  @pending = Transaction.where("buyer_id = ? AND status = ? AND transaction_type= ?",
                                  current_user.id,
                                  Transaction.statuses[:pending],
                                  Transaction.transaction_types[:withdraw]
                                  ).sum(:amount)

  @purchased = Transaction.where("buyer_id = ? AND source_type = ? AND transaction_type= ?",
                                  current_user.id,
                                  Transaction.source_types[:system],
                                  Transaction.transaction_types[:trans]
                                  ).sum(:amount)

  @withdrawable = current_user.wallet

  @transactions = Transaction.where("seller_id = ? OR (buyer_id= ? AND source_type= ?)",
                  current_user.id,
                  current_user.id,
                  Transaction.source_types[:system]
                  ).page(params[:page])
end

def withdraw
  amount = params[:amount].to_i
  is_pending_withdraw = Transaction.exists?(buyer_id: current_user.id,
                                          status: Transaction.statuses[:pending],
                                          transaction_type: Transaction.transaction_types[:withdraw])
  if amount <= 0
    flash[:alert] = "Invalid amount"
  elsif amount > current_user.wallet
    flash[:alert] = "You're asking for more than you have"
  elsif !is_pending_withdraw.blank?
    flash[:alert] = "You currently have a pending witdraw request"
  else
    transaction = Transaction.new
    transaction.status = Transaction.statuses[:pending]
    transaction.transaction_type = Transaction.transaction_types[:withdraw]
    transaction.source_type = Transaction.source_types[:system]
    transaction.buyer = current_user
    transaction.amount = amount

    if transaction.save
      flash[:notice] ="Create withdraw resquest successfully"
    else
      flash[:alert] = "Cannot create a request"
    end
  end
  redirect_to request.referrer
end
  private
  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                              <figure class="image is-128x128">
                               <%= image_tag avatar_url(current_user), class:"is-rounded" %>
                              </figure>
                            </div>

                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                  <p class="title is-5">
                                    <%= current_user.full_name %>
                                    </p>

                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post do |f| %>
                                    <div class="file">
                                      <label class="button is-primary is-outlined is-fullwidth">
                                        <%= f.file_field :avatar, class:"file-input", onchange: "this.form.submit();"%>
                                        <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp; Upload avatar
                                      </label>

                                    </div>
                                    <% end %>

                                </div>
                                <hr class="h-10">

                                <!-- Member -->
                                <article class="media">
                                  <div class="media-content">Member since</div>
                                  <div class="media-right">
                                    <strong> <%= current_user.created_at.strftime('%b %y')%></strong>
                                  </div>

                                </article>
                                <hr class="h-10">

                                <!-- From -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">From
                                    </div>
                                    <div class="media-right">
                                    <strong> <%= current_user.from%></strong>
                                    <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                  </div>
                                </div>
                                  <div class="content">
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: "user-from", class:"is-hidden"} do |f| %>
                                    <div class="field">
                                      <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input' %>
                                    </div>
                                    <a class="toggle button is-light" aria-controls="user-from"=>Cancel</a>
                                    <%= f.submit "Save", class:"button is-danger" %>
                                  <% end %>
                                  </div>

                                </article>
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">Online status</div>
                                    <div class="media-right">
                                    <strong> <% if current_user.status%>
                                      Online
                                    <%else %>
                                      Offline
                                    <% end %>
                                    </strong><i class="toggle far fa-edit" aria-controls="user-status"></i>
                                  </div>
                                </div>

                                  <div class="content">
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: "user-status", class:"is-hidden"} do |f| %>
                                    <div class="field">
                                      <%= f.select(:status, options_for_select([["Online", true], ["Offline", false]]), {}, {class: "select is-fullwidth"}) %>
                                    </div>
                                    <a class="toggle button is-light" aria-controls="user-status">Cancel</a>
                                    <%= f.submit "Save", class:"button is-danger" %>
                                  <% end %>
                                  </div>


                                </article>

                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                  <div class="media">
                                    <div class="media-content">
                                      <p>
                                        <strong>About yourself</strong>
                                        <br>
                                      <%= current_user.about %>
                                      </p>
                                    </div>
                                    <div class="media-right">
                                    <i class="toggle far fa-edit" aria-controls="user-about"></i>
                                  </div>
                                </div>
                                  <div class="content">
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: "user-about", class:"is-hidden"} do |f| %>
                                    <div class="field">
                                      <%= f.text_field :about, autofocus: true, autocomplete: 'form', class: 'input' %>
                                    </div>
                                    <a class="toggle button is-light" aria-controls="user-about"=>Cancel</a>
                                    <%= f.submit "Save", class:"button is-danger" %>
                                  <% end %>
                                  </div>
                                </article>
                                <hr class="h-10">

                                <!-- Languages -->
                                <article>
                                     <div class="media">
                                    <div class="media-content">
                                      <p>
                                        <strong>Langage</strong>
                                        <br>
                                      <%= current_user.language %>
                                      </p>
                                    </div>
                                    <div class="media-right">
                                    <i class="toggle far fa-edit" aria-controls="user-language"></i>
                                  </div>
                                </div>
                                  <div class="content">
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: "user-language", class:"is-hidden"} do |f| %>
                                    <div class="field">
                                      <%= f.text_area :language, autofocus: true, autocomplete: 'form', class: 'input' %>
                                    </div>
                                    <a class="toggle button is-light" aria-controls="user-language"=>Cancel</a>
                                    <%= f.submit "Save", class:"button is-danger" %>
                                  <% end %>
                                  </div>
                                </article>
                                <hr class="h-10">

                                <!-- Linked Account -->
                                <article class="media"></article>

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                     <div class="column is-one-third has-text-centered">
                        <%= link_to new_gig_path do %>
                          <div class="card">

                              <div class="card-image card-content is-horizontal-center is-flex ">
                                  <figure class="image is-128x128 ">
                                      <%= image_tag 'icon_add.png'%>
                              </div>

                              <div class="card-content">
                                  <strong>Create a new gig</strong>
                              </div>

                          </div>
                      <% end %>
                    </div>

                    <!-- Sample Gig -->
                    <% current_user.gigs.each do |gig| %>
                    <div class="column is-one-third">
                        <div class="card">

                            <div class="card-image">
                                <%= link_to edit_gig_path(gig) do %>
                                <figure class="image is-4by3">
                                    <%= image_tag gig_cover(gig) %>
                                </figure>
                                <% end %>
                            </div>

                            <div class="card-content p-t-5 p-b-5">
                                <p class="subtitle is-6 m-b-5"><%= link_to gig.title, gig_path(gig) %></p>
                                <span class="star-review"><i class="fa fa-star"></i>
                                    <%= gig.average_rating %>
                                     <span class="has-text-primary">
                                    <%= gig.reviews.count %>
                                     </span>
                                </span>
                            </div>

                            <footer class="card-footer">
                                <% basic_price = gig.pricings.find { |p|p.pricing_type =='basic'} %>
                                <a class="has-text-danger is-block card-footer-item has-text-right">
                                  <% if !basic_price.nil? %>
                                    <span class="small-title">STARTING AT</span>
                                    <strong>$ <%= basic_price.price%></strong>
                                  <% else %>
                                    <strong>
                                      <span class="small-title has-text-dark">No pricing yet</span>
                                    </strong>
                                  <% end %>
                                </a>
                            </footer>

                        </div>
                    </div>
              <% end %>

                </div>
            </div>

        </div>
    </div>
</section>

app/views/users/payout.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8-tablet is-6-desktop is-6-widescreen">
          <p class="title has-text-centered">Payout Method</p>

          <%= form_with url: update_payout_path, local: true do |f| %>
          <div class="field">
            <%= f.text_field :paypal, value: current_user.paypal, placeholder: "Your Paypal email", class:"input"%>
          </div>
          <div class="field is-grouped is-grouped-centered">
            <%= f.submit "Save", class:"button is-primary"%>
          </div>
        <% end %>


  </div>
</div>
</div>
</section>

app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                              <figure class="image is-128x128">
                               <%= image_tag avatar_url(@user), class:"is-rounded" %>
                              </figure>
                            </div>

                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                  <p class="title is-5">
                                    <%= @user.full_name %>
                                   </p>
                                    <% if current_user.id != @user.id %>
                                    <a class="button is-black is-outline is-fullwidth toggle-contact">Contact me</a>
                                    <% end %>
                                </div>
                                <hr class="h-10">

                                <!-- Member -->
                                <article class="media">
                                  <div class="media-content">Member since</div>
                                  <div class="media-right">
                                    <strong> <%= @user.created_at.strftime('%b %y')%></strong>
                                  </div>

                                </article>
                                <hr class="h-10">

                                <!-- From -->
                                <article class="media">

                                    <div class="media-content">From
                                    </div>
                                    <div class="media-right">
                                    <strong> <%= @user.from%></strong>
                                  </div>


                                </article>
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article class="media">
                                    <div class="media-content">Online status</div>
                                    <div class="media-right">
                                    <strong> <% if @user.status%>
                                      Online
                                    <%else %>
                                      Offline
                                    <% end %></strong>
                                  </div>


                                </article>

                            </div>
                        </div>
                    </div>


                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article class="media">
                                    <div class="media-content">
                                      <p>
                                        <strong>About yourself</strong>
                                        <br>
                                      <%= @user.about %>
                                      </p>
                                    </div>
                                    <div class="media-right">
                                  </div>
                                </article>
                                <hr class="h-10">

                                <!-- Languages -->
                                <article class="media">

                                    <div class="media-content">
                                      <p>
                                        <strong>Langage</strong>
                                        <br>
                                      <%= @user.language %>
                                      </p>
                                    </div>
                                    <div class="media-right">
                                  </div>


                                </article>
                                <hr class="h-10">

                                <!-- Linked Account -->
                                <article class="media"></article>

                            </div>
                        </div>
                    </div>
            </div>
          </div>

            <!-- RIGHT SIDE -->
            <div class="column">


                    <div class="columns is-multiline">
                    <!-- Sample Gig -->
                    <% @user.gigs.each do |gig| %>
                    <div class="column is-one-third">
                        <div class="card">

                            <div class="card-image">
                                <%= link_to edit_gig_path(gig) do %>
                                <figure class="image is-4by3">
                                    <%= image_tag gig_cover(gig) %>
                                </figure>
                                <% end %>
                            </div>

                            <div class="card-content p-t-5 p-b-5">
                                <p class="subtitle is-6 m-b-5"><%= link_to gig.title, gig_path(gig) %></p>
                                <span class="star-review"><i class="fa fa-star"></i>
                                    <%= gig.average_rating %>
                                     <span class="has-text-primary">
                                    <%= gig.reviews.count %>
                                     </span>
                                </span>
                            </div>

                            <footer class="card-footer">
                                <% basic_price = gig.pricings.find { |p|p.pricing_type =='basic'} %>
                                <a class="has-text-danger is-block card-footer-item has-text-right">
                                  <% if !basic_price.nil? %>
                                    <span class="small-title">STARTING AT</span>
                                    <strong>$ <%= basic_price.price%></strong>
                                  <% else %>
                                    <strong>
                                      <span class="small-title has-text-dark">No pricing yet</span>
                                    </strong>
                                  <% end %>
                                </a>
                            </footer>

                        </div>
                    </div>
              <% end %>

            </div>
               <div class="card">
                 <div class="card-header">
                   <div class="card-header-title">
                     Last reviews
                   </div>
                 </div>
                 <div class="card-content">
                  <!--sample reviews -->

                  <% @reviews.each do |r| %>
                  <article class="media p-t-5">
                   <figure class="media-left">
                    <p class="image is-64x64">
                    <%= image_tag avatar_url(r.buyer), class:"is-rounded" %>
                    </p>
                    </figure>
                    <div class="media-content">
                      <div class="content">
                          <p><strong><%= r.buyer.full_name %></strong><br>
                            <%= r.review %>
                          </p>
                          <small><%= time_ago_in_words(r.created_at) %></small>
                      </div>
                    </div>
                    <div class="media-right">
                      <span class="star-review"><i class="fa fa-star"></i><%= r.stars%></span>
                    </div>
                  </article>
                <% end %>
                 </div>
               </div>
            </div>

        </div>
    </div>
</section>

<div class="modal" id="contact-form">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Send a Message</p>
            <button class="delete toggle-contact" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="columns">
                <div class="column is-one-third">
                    <div class="card" st>
                        <div class="card-content is-horizontal-center is-flex">
                            <figure class="image is-128x128">
                                    <%= image_tag avatar_url(@user), class:"is-rounded"%>
                            </figure>
                        </div>
                        <div class="card-content">
                            <hr>
                            <strong>Please include:</strong>
                            <ul class="is-size-7" style="list-style:initial">
                                <li>Project description</li>
                                <li>Specific instructions</li>
                                <li>Relevant files</li>
                                <li>Your budget</li>
                            </ul>
                        </div>
                     </div>
                </div>
                <div class="column">
                  <%= form_with model: Message.new do |f| %>
                  <%= f.hidden_field :receiver_id, value: @user.id %>
                    <div class="card-content">
                        <div class="field">
                            <div class="control">
                                <%= f.text_area :content, class:"textarea"%>
                            </div>
                        </div>
                        <%= f.submit "Send", class:"button is-danger is-pulled-right"%>
                    </div>
                    <% end %>
                </div>
            </div>
        </section>
    </div>
</div>
<script>
    var toggle_modals = $('.toggle-contact');
    if (toggle_modals) {
        toggle_modals.on('click', function(event) {
            event.stopPropagation();
            event.preventDefault();
            var form = document.getElementById('contact-form');
            form.classList.toggle('is-active');
        });
    }
</script>